/*
 * Copyright 2016 Alex Andres
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_stylus_StylusManager */

#ifndef _Included_org_lecturestudio_stylus_StylusManager
#define _Included_org_lecturestudio_stylus_StylusManager
#ifdef __cplusplus
extern "C" {
#endif

	/*
	* Class:     org_lecturestudio_stylus_StylusManager
	* Method:    initialise
	* Signature: ()V
	*/
	JNIEXPORT void JNICALL Java_org_lecturestudio_stylus_StylusManager_initialize
		(JNIEnv *, jobject);

	/*
	 * Class:     org_lecturestudio_stylus_StylusManager
	 * Method:    destroy
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_org_lecturestudio_stylus_StylusManager_destroy
		(JNIEnv *, jobject);

	/*
	* Class:     org_lecturestudio_stylus_StylusManager
	* Method:    attachStylusListener
	* Signature: (Lorg_lecturestudio_stylus/StylusListener;Ljava/lang/Object;)V
	*/
	JNIEXPORT void JNICALL Java_org_lecturestudio_stylus_StylusManager_attachStylusListener
		(JNIEnv *, jobject, jobject, jobject);

	/*
	 * Class:     org_lecturestudio_stylus_StylusManager
	 * Method:    detachStylusListener
	 * Signature: (Lorg_lecturestudio_stylus/StylusListener;Ljava/lang/Object;)V
	 */
	JNIEXPORT void JNICALL Java_org_lecturestudio_stylus_StylusManager_detachStylusListener
		(JNIEnv *, jobject, jobject, jobject);
	
	/*
	 * Class:     org_lecturestudio_stylus_StylusManager
	 * Method:    enableStylusListener
	 * Signature: (Lorg_lecturestudio_stylus/StylusListener;B)V
	 */
	JNIEXPORT void JNICALL Java_org_lecturestudio_stylus_StylusManager_enableStylusListener
	(JNIEnv *, jobject, jobject, jboolean);

	/*
	 * Class:     org_lecturestudio_stylus_StylusManager
	 * Method:    getDevices
	 * Signature: ()Lorg_lecturestudio_stylus/StylusDevice;
	 */
	JNIEXPORT jobject JNICALL Java_org_lecturestudio_stylus_StylusManager_getDevices
		(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
